// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApproveDocument(arg1) {
  return window['go']['main']['App']['ApproveDocument'](arg1);
}

export function AskAssistant(arg1) {
  return window['go']['main']['App']['AskAssistant'](arg1);
}

export function CreateFolder(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateFolder'](arg1, arg2, arg3);
}

export function DeleteDocument(arg1) {
  return window['go']['main']['App']['DeleteDocument'](arg1);
}

export function DeleteFolder(arg1) {
  return window['go']['main']['App']['DeleteFolder'](arg1);
}

export function DownloadDocumentFile(arg1) {
  return window['go']['main']['App']['DownloadDocumentFile'](arg1);
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetDocumentPreview(arg1) {
  return window['go']['main']['App']['GetDocumentPreview'](arg1);
}

export function IngestFile(arg1, arg2) {
  return window['go']['main']['App']['IngestFile'](arg1, arg2);
}

export function ListDocuments(arg1) {
  return window['go']['main']['App']['ListDocuments'](arg1);
}

export function ListFolders() {
  return window['go']['main']['App']['ListFolders']();
}

export function OpenDocumentFile(arg1) {
  return window['go']['main']['App']['OpenDocumentFile'](arg1);
}

export function RejectDocument(arg1) {
  return window['go']['main']['App']['RejectDocument'](arg1);
}

export function Search(arg1) {
  return window['go']['main']['App']['Search'](arg1);
}

export function SelectDocumentFile() {
  return window['go']['main']['App']['SelectDocumentFile']();
}

export function UpdateDocumentClassification(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateDocumentClassification'](arg1, arg2, arg3);
}
