// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';
import {folders} from '../models';
import {main} from '../models';
import {documents} from '../models';

export function ApproveDocument(arg1:string):Promise<void>;

export function AskAssistant(arg1:string):Promise<backend.AssistantAnswer>;

export function CreateFolder(arg1:string,arg2:string,arg3:boolean):Promise<folders.Folder>;

export function DeleteDocument(arg1:string):Promise<void>;

export function DeleteFolder(arg1:string):Promise<void>;

export function DownloadDocumentFile(arg1:string):Promise<string>;

export function GetAppInfo():Promise<main.AppInfo>;

export function GetDocumentPreview(arg1:string):Promise<main.DocumentPreview>;

export function IngestFile(arg1:string,arg2:string):Promise<documents.Document>;

export function ListDocuments(arg1:string):Promise<Array<documents.Document>>;

export function ListFolders():Promise<Array<folders.Folder>>;

export function OpenDocumentFile(arg1:string):Promise<void>;

export function RejectDocument(arg1:string):Promise<void>;

export function Search(arg1:string):Promise<backend.SearchResponse>;

export function SelectDocumentFile():Promise<string>;

export function UpdateDocumentClassification(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;
